# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BuscarProfesor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(200, 94)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Seleccion = QtWidgets.QComboBox(self.centralwidget)
        self.Seleccion.setGeometry(QtCore.QRect(20, 10, 171, 22))
        self.Seleccion.setObjectName("Seleccion")
        self.Seleccion.addItem("")
        self.Seleccion.addItem("")
        self.Trabajodegrado = QtWidgets.QPushButton(self.centralwidget)
        self.Trabajodegrado.setGeometry(QtCore.QRect(60, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Trabajodegrado.setFont(font)
        self.Trabajodegrado.setCheckable(False)
        self.Trabajodegrado.setAutoDefault(False)
        self.Trabajodegrado.setObjectName("Trabajodegrado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Seleccion.setItemText(0, _translate("MainWindow", "Ing Troncoso"))
        self.Seleccion.setItemText(1, _translate("MainWindow", "Ing Diaz"))
        self.Trabajodegrado.setText(_translate("MainWindow", "Buscar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
