# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Frente.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Resumen(object):
    def setupUi(self, Resumen):
        Resumen.setObjectName("Resumen")
        Resumen.resize(518, 438)
        self.centralwidget = QtWidgets.QWidget(Resumen)
        self.centralwidget.setObjectName("centralwidget")
        self.Trabajodegrado = QtWidgets.QPushButton(self.centralwidget)
        self.Trabajodegrado.setGeometry(QtCore.QRect(20, 40, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Trabajodegrado.setFont(font)
        self.Trabajodegrado.setCheckable(False)
        self.Trabajodegrado.setAutoDefault(False)
        self.Trabajodegrado.setObjectName("Trabajodegrado")
        self.Profesores = QtWidgets.QPushButton(self.centralwidget)
        self.Profesores.setGeometry(QtCore.QRect(20, 320, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Profesores.setFont(font)
        self.Profesores.setObjectName("Profesores")
        self.Calendario = QtWidgets.QPushButton(self.centralwidget)
        self.Calendario.setGeometry(QtCore.QRect(20, 230, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Calendario.setFont(font)
        self.Calendario.setObjectName("Calendario")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 140, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.Logo = QtWidgets.QPushButton(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(280, 120, 221, 211))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Logo.setFont(font)
        self.Logo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Sistemas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Logo.setIcon(icon)
        self.Logo.setIconSize(QtCore.QSize(200, 200))
        self.Logo.setObjectName("Logo")
        Resumen.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Resumen)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 518, 21))
        self.menubar.setObjectName("menubar")
        Resumen.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Resumen)
        self.statusbar.setObjectName("statusbar")
        Resumen.setStatusBar(self.statusbar)

        self.retranslateUi(Resumen)
        QtCore.QMetaObject.connectSlotsByName(Resumen)

    def retranslateUi(self, Resumen):
        _translate = QtCore.QCoreApplication.translate
        Resumen.setWindowTitle(_translate("Resumen", "MainWindow"))
        self.Trabajodegrado.setText(_translate("Resumen", "Trabajos de grado"))
        self.Profesores.setText(_translate("Resumen", "Profesores"))
        self.Calendario.setText(_translate("Resumen", "Calendario"))
        self.pushButton_4.setText(_translate("Resumen", "Resumen data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Resumen = QtWidgets.QMainWindow()
    ui = Ui_Resumen()
    ui.setupUi(Resumen)
    Resumen.show()
    sys.exit(app.exec_())
