# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pregunta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(518, 108)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Trabajodegrado = QtWidgets.QPushButton(self.centralwidget)
        self.Trabajodegrado.setGeometry(QtCore.QRect(20, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Trabajodegrado.setFont(font)
        self.Trabajodegrado.setCheckable(False)
        self.Trabajodegrado.setAutoDefault(False)
        self.Trabajodegrado.setObjectName("Trabajodegrado")
        self.Trabajodegrado_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Trabajodegrado_2.setGeometry(QtCore.QRect(270, 10, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Trabajodegrado_2.setFont(font)
        self.Trabajodegrado_2.setCheckable(False)
        self.Trabajodegrado_2.setAutoDefault(False)
        self.Trabajodegrado_2.setObjectName("Trabajodegrado_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 518, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Trabajodegrado.setText(_translate("MainWindow", "Buscar"))
        self.Trabajodegrado_2.setText(_translate("MainWindow", "Agregar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
